CREATE TABLE IF NOT EXISTS clients (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name  VARCHAR(255) NOT NULL,
  email VARCHAR(255) NULL,
  note  TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
